# Generated by Django 4.2.19 on 2025-03-31 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('other_names', models.CharField(max_length=255)),
                ('total_folia', models.IntegerField()),
                ('laod_folia', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('place_of_origin', models.CharField(max_length=255)),
                ('materials', models.CharField(max_length=100)),
                ('format_description', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('image_src', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='collation.manuscript')),
            ],
            options={
                'unique_together': {('manuscript', 'verse_number')},
            },
        ),
    ]
