# Generated by Django 5.1.7 on 2025-04-27 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0002_manuscript_verse'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField()),
                ('word1', models.CharField(max_length=255)),
                ('word2', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('manuscript_sigla', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_significant', models.BooleanField()),
                ('variation_type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('word_comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collation.wordcomparison')),
            ],
        ),
    ]
